import {
  CREATE,
  DELETE,
  GET_LIST,
  GET_MANY,
  GET_ONE,
  GET_MANY_REFERENCE,
  UPDATE
} from 'admin-on-rest';

const QUERY_TYPES = [GET_LIST, GET_MANY, GET_MANY_REFERENCE, GET_ONE];
const MUTATION_TYPES = [CREATE, DELETE, UPDATE];

export {
  CREATE,
  DELETE,
  GET_LIST,
  GET_MANY,
  GET_ONE,
  GET_MANY_REFERENCE,
  MUTATION_TYPES,
  QUERY_TYPES,
  UPDATE,
};
